package com.rubyko.rmi;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'yegor' at '2/23/16 5:46 AM' with Gradle 2.6
 *
 * @author yegor, @date 2/23/16 5:46 AM
 */
public class LibraryTest {
	
	
	@Test
	public void testSomeLibraryMethod() {
    }
	
	
}
